template = "https://github.com/giellalt/template-lang-und"
rev_id = 328
template_sha = "a66ce6606ea33e46cd3439c88cafa44d4dcdde92"

[replacements]
__GLOTTOLOG_ID__ = "plai1258"
__REPO__ = "lang-crk"
__UND2C__ = "crk"
__UNDEFINED__ = "Plains Cree"
__UND__ = "crk"
