template = "https://github.com/giellalt/template-lang-und"
rev_id = 311
template_sha = "c4d2b17b988e0fed439969cd55ec0e02eb7d2e4b"

[replacements]
__GLOTTOLOG_ID__ = "plai1258"
__REPO__ = "lang-crk"
__UND2C__ = "crk"
__UNDEFINED__ = "Plains Cree"
__UND__ = "crk"
