template = "https://github.com/giellalt/template-lang-und"
rev_id = 334
template_sha = "295433261311db06974764ace81fbb35d1f5ac28"

[replacements]
__GLOTTOLOG_ID__ = "plai1258"
__REPO__ = "lang-crk"
__UND2C__ = "crk"
__UNDEFINED__ = "Plains Cree"
__UND__ = "crk"
