[package]
name = "crk"
human_name = "Plains Cree"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.crk]
filename = "crk-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-crk"
platform = "windows"
uuid = "55A81174-4234-4E81-9EFE-88175952CD70"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.crk"
package = "speller-crk"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-crk-mso"
platform = "windows"
uuid = "A9726CC0-EB2D-4C93-B2F1-9EA8276F3818"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-crk"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
