# Readme:
# manifest.toml needs to contain the manifest for the spellers
# The Divvun CI encryption key 'DIVVUN_KEY' needs to be added as a secret 

name: "Build Speller Archives and Bundles"
on: push

jobs:
  build:
    runs-on: self-hosted
    container: ubuntu:18.04
    outputs:
      speller-paths: ${{ steps.build.outputs['speller-paths'] }}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: giellalt/giella-core
          path: giella-core
      - uses: actions/checkout@v2
        with:
          repository: giellalt/giella-shared
          path: giella-shared
      - uses: actions/checkout@v2
        with:
          path: lang
      - name: Install dev dependencies
        uses: divvun/actions/lang/install-deps@refactor
        with:
          sudo: false
      - name: Build
        id: build
        uses: divvun/actions/lang/build@refactor
        with:
          fst: hfst
          force-desktop-spellers-as-mobile: true
      - name: Upload spellers
        uses: actions/upload-artifact@v2
        with:
          name: spellers
          path: 'lang/build/tools/spellcheckers/*.zhfst'
  bundle:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - type: speller-macos
            os: macos-latest
          - type: speller-mobile
            os: macos-latest
          - type: speller-windows
            os: windows-latest
          - type: speller-windows-msoffice
            os: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Divvun CI
        uses: divvun/actions/setup@refactor
        with:
          key: ${{ secrets.DIVVUN_KEY }}
      - name: Download Spellers
        uses: actions/download-artifact@v2
        with:
          name: spellers
      - name: Install build tools from Pahkat for Windows
        if: ${{ matrix.type == 'speller-windows' || matrix.type == 'speller-windows-msoffice' }}
        uses: divvun/actions/pahkat/init@refactor
        with:
          repo: https://pahkat.uit.no/devtools/
          channel: nightly
          packages: divvun-bundler, pahkat-uploader, win-reg-tool
      - name: Install build tools from Pahkat for macOS
        if: ${{ matrix.type == 'speller-macos' || matrix.type == 'speller-mobile' }}
        uses: divvun/actions/pahkat/init@refactor
        with:
          repo: https://pahkat.uit.no/devtools/
          channel: nightly
          packages: divvun-bundler, pahkat-uploader, thfst-tools, xcnotary
      - name: Run Divvun Bundler
        id: bundler
        uses: divvun/actions/speller/bundle@refactor
        with:
          speller-type: ${{ matrix.type }}
          speller-manifest-path: "manifest.toml"
          speller-paths: ${{ needs.build.outputs['speller-paths'] }}
      - name: Deploy to Pahkat
        uses: divvun/actions/speller/deploy@refactor
        with:
          speller-type: ${{ matrix.type }}
          speller-manifest-path: "manifest.toml"
          payload-path: "${{ steps.bundler.outputs['payload-path'] }}"
          version: "${{ steps.bundler.outputs.version }}"
          channel: nightly
          force-deploy: true

